---

port: 80
host: localhost
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Rice Launch - Rice's Undergraduate Entrepreneurship Group"
keywords:    "Rice, Rice University, Rice Launch, Launch, Entrpreneurship, Entrepreneur"
description: "Rice Entrepreneurs"
source_link: "http://RiceLaunch.com"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:  UA-65724448-1## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  darkgrey:  '#404749'
